# Generated by Django 4.2.13 on 2024-07-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_user_remove_product_vertical_product_vertical_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='egg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='milk',
            field=models.IntegerField(default=0),
        ),
    ]
