# Generated by Django 4.2.13 on 2024-07-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_product_egg_product_milk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='coffee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='flour',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sugar',
            field=models.IntegerField(default=0),
        ),
    ]
